name: notifications
description: A new Flutter package project.
version: 0.0.2
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  badges: ^3.1.2
  dart_mappable: ^4.2.2
  firebase_messaging: ^14.7.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
<<<<<<< HEAD
  cloud_functions: ^4.7.5
  utilities:
    # git:
    #   url: git@github.com:digital-oasis-llc-fz/utilities.git
    #   ref: v0.0.1
    path: ../../packages/utilities
=======
  flutter_timezone: ^1.0.8
>>>>>>> e2c0d9a28d92669ca254504fbb66dc030dd5f623
  navigation:
    path: ../../packages/navigation
  universal_io: ^2.2.2
  utilities:
    path: ../../packages/utilities

dev_dependencies:
  build_runner: null
  dart_mappable_builder: ^4.2.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mobx_codegen: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
