name: packages

# MELOS_PACKAGE_LIST
packages:
  - admob
  - authentication
  - deeplinks
  - navigation
  - notifications
  - theme
  - utilities
  - widgets
  - fonts
  - maps
  - forms
  - socials
  - youtube
  - contacts
  - youtube
  - text_recognition
  - media
  - storage
  - screen_capture_event
  - payment
  # MELOS_PACKAGE_LIST_END

scripts:
  analyze:
    exec: dart analyze .
  gen:
    exec: "dart pub run build_runner build --delete-conflicting-outputs"
  fix:
    exec: "dart fix --dry-run"

  upgrade:
    exec: "dart pub upgrade --major-versions"

  version:
    hooks:
      preCommit:
        exec: melos gen && melos format && melos clean

command:
  clean:
    hooks:
      post: melos exec --flutter --concurrency=3 -- "flutter clean && flutter pub get"
