name: packages

scripts:
  clean: melos clean
  upgrade: melos run upgrade

environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  melos: ^5.2.2
dependencies:
  dio: ^5.4.2+1
  firebase_crashlytics: ^4.0.0
  flutter_contacts: ^1.1.7+1
  universal_io: ^2.2.2
  equatable: ^2.0.5
