name: packages

environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  melos: ^5.2.2
dependencies:
  dio: ^5.4.2+1
  firebase_crashlytics: ^3.5.5
  flutter_contacts: ^1.1.7+1
  universal_io: ^2.2.2
