import "package:widgets/images/options/abstract.dart";

class MemoryImageOptions extends ImageOptions {
  const MemoryImageOptions({
    super.frameBuilder,
    super.errorBuilder,
    // super.semanticLabel,
    // super.excludeFromSemantics,
    super.width,
    super.height,
    super.color,
    super.opacity,
    super.colorBlendMode,
    super.fit,
    super.alignment,
    super.repeat,
    super.centerSlice,
    super.matchTextDirection,
    super.gaplessPlayback,
    // super.isAntiAlias,
    super.filterQuality,
    super.imageBuilder,
    super.placeholder,
    super.progressIndicatorBuilder,
    super.errorWidget,
    super.fadeOutDuration,
    super.fadeOutCurve,
    super.fadeInDuration,
    super.fadeInCurve,
    super.cacheManager,
    super.useOldImageOnUrlChange,
    super.placeholderFadeInDuration,
    super.memCacheWidth,
    super.memCacheHeight,
    super.cacheKey,
    super.maxWidthDiskCache,
    super.maxHeightDiskCache,
    super.errorListener,
    super.imageRenderMethodForWeb,
  }) : super(loadingBuilder: null);
}
