name: maps
description: "A new Digital Oasis package project."
version: 0.0.2
homepage: null
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  uuid: ^4.0.0 # Temporary fix for uuid v3.0.7, used for mapbox_search API🤩

dependencies:
  dart_mappable: ^4.2.2
  flutter:
    sdk: flutter
  flutter_map:
  flutter_map_animations:
  # Github path neccessary until main branch gets updated with flutter_map v6 support
  flutter_map_supercluster:
    git:
      url: https://github.com/rorystephenson/flutter_map_supercluster.git
      ref: v5
  latlong2:
  url_launcher: ^6.2.6
  utilities:
    path: ../utilities
  theme:
    path: ../theme
  forms:
    path: ../forms
  mapbox_search: ^4.2.0
  dropdown_search: ^5.0.6
  flutter_map_cancellable_tile_provider: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.9
  dart_mappable_builder: ^4.2.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mobx_codegen: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
